### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by navidcy**
This PR adds proper acknowledgement to the logo creator. Something that was purposely, or carelessly, missed by @josuemtzmo's original README version.

### CODE REVIEW

**Comment by navidcy** [comment]
@josuemtzmo I'm allowing you the chance to review.

But I won't accept any suggestions that remove your name from the readme. Acknowledgment is in order.

**Comment by navidcy** [comment]
I decided it's better for someone else, other than @josuemtzmo,  to review this.

**Review by josuemtzmo — COMMENTED** [review]
I am happy with the changes, as it reads smoothly.

**Comment by navidcy** [comment]
If you are happy why don't you approve the PR? :)

**Comment by navidcy** [comment]
Great!

**Pull request merged**
